### ISSUE TITLE
Add support for shared memory

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/seed-cli#118]
We have a need to support to the runner for algorithms using shared memory.

The resources will need to be introspected for `sharedMem` in the `job.resources` member.

Implementation will likely be done here: 
https://github.com/ngageoint/seed-cli/blob/6c7cd0cca4741b4a2ab3d29f051de125d2acbae5/commands/run.go#L451

**Comment by JohnPTobe** [comment]
Fixed by commit https://github.com/ngageoint/seed-cli/commit/ecb640a0d66bd194c58b8c8d648b8e2fb960079a
