### ISSUE TITLE
Apostrophe's break seed label unmarshalling

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/seed-cli#124]
Putting apostrophe's in error descriptions (and likely other fields) breaks unmarshalling seed manifests from docker labels.  We likely need to add special handling much like for quotation marks, dollar signs, etc.  If this is not feasible we may want to disallow them in all fields.

**Comment by JohnPTobe** [comment]
Unable to reproduce this on the low side.

**Comment by gisjedi** [comment]
Closed as #178 covers this issue specifically.
