### ISSUE TITLE
Environment variable injection

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/seed-cli#132]
CLI fails to conform to the Seed specification on a number of points with regard to environment variable injection. Ref: https://ngageoint.github.io/seed/master/#variable-injection

Specifically, it fails on the following requirements:

* `OUTPUT_DIR` must indicate the absolute location that all job outputs are to be written to.
* All `name` member values of `resources.scalar` elements MUST map to environment variables.
* All `name` member values of `interface.inputs.files` elements MUST map to environment variables.
* All `name` member values of `interface.inputs.json` elements MUST map to environment variables.

**Comment by JohnPTobe** [comment]
Lol, just found this myself working on my seed consumer validation script.  I'll have a fix tonight or early tomorrow morning.

**Comment by JohnPTobe** [comment]
It also fails to inject environment variables from settings elements into the command string.
