### ISSUE TITLE
Add gitlab ci build

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/seed-cli#146]
Add a gitlab ci build for building and testing seed-cli images on high side.

**Comment by drewmccal** [comment]
This would be useful for me as well.  github.com/zyxar/image2ascii/ascii is not available on the high side gitlab to my knowledge.

**Comment by JohnPTobe** [comment]
I'm not sure this would help you; we bundle libraries like that in our project and bring it up together in our internal project so it's still not available by itself

**Comment by JohnPTobe** [comment]
This has been addressed.  We need to fix testing on high side but the binaries are built on the high side now in gitlab.
