### ISSUE TITLE
job automatically fails if anything is written to stderr

### ISSUE THREAD

**Issue by Fizz11** [ngageoint/seed-cli#162]
A job can complete successfully but seed will still declare a failed run if anything is written to stderr. success should be determined solely by a jobs exit code. 

see code starting here https://github.com/ngageoint/seed-cli/blob/master/commands/run.go#L195

**Comment by JohnPTobe** [comment]
We want to also change the run command to display running output from the job unless the quiet flag is specified. Currently all output is held until docker run finishes.
