### ISSUE TITLE
Environment variables normalization missed for inputs and settings

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/seed-cli#164]
The environment variables must follow normalization rules as defined in https://ngageoint.github.io/seed/seed.html#variable-injection. Presently the command environment placeholders are properly normalized, but not the environment variables themselves. This causes a mismatching of command with `${MY_INPUT}` and actual environment injection of `my_input` when an input name is defined in `job.interface.inputs.json` or `job.interface.inputs.files` as `my_input`.

From a quick look, it looks like both https://github.com/ngageoint/seed-cli/blob/master/commands/run.go#L262, https://github.com/ngageoint/seed-cli/blob/master/commands/run.go#L362 and https://github.com/ngageoint/seed-cli/blob/master/commands/run.go#L520 `key` values need to be normalized. 

We also must add examples that verify this functionality. This means for `job.interface.inputs.json`, `job.interface.inputs.json`, and `job.interface.settings` there must be mixed case names to ensure environment variable injection is properly handled.

**Comment by emimaesmith** [comment]
Closed via #165
