### ISSUE TITLE
ASCII art for the CLI help

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/seed-cli#173]
We want the logo integrated from https://github.com/ngageoint/seed/blob/master/spec/images/logo.png as ASCII art when the cli help is displayed. I'd like for it to be color if possible. This go library can do it. https://github.com/zyxar/image2ascii/blob/master/ascii/ascii.go

I'd prefer to generate a one-time ascii art image and embed as an asset in the CLI binary, but embedding the png and then doing a runtime generation is fine as well.

Something like the attached...
![screen shot 2018-08-14 at 2 41 20 pm](https://user-images.githubusercontent.com/4768496/44111424-5f562aac-9fd0-11e8-884e-d7152e428f41.png)

**Comment by emimaesmith** [comment]
Seed logo added whenever a seed command help is initiated:

![screen shot 2018-08-16 at 2 13 11 pm](https://user-images.githubusercontent.com/29577288/44226628-9266ab80-a15e-11e8-9528-5cda327d40ff.png)
