### ISSUE TITLE
Seed Spec does nothing

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/seed-cli#197]
The spec command currently just displays the main help. Has this command been implemented? If not it should probably be removed from the list of commands until it is.

**Comment by emimaesmith** [comment]
@JohnPTobe It was implemented. It requires the seed spec man page file (generated by the seed spec project) to be installed along with the seed-cli. 

https://github.com/ngageoint/seed/issues/113

**Comment by JohnPTobe** [comment]
Thanks, I'll close this after testing it tomorrow morning.

**Comment by JohnPTobe** [comment]
Um, I don't think this has been implemented.  I don't see any code in main parsing the spec command and this issue is still open: #140.

**Comment by emimaesmith** [comment]
Looks like the code for this implementation was never merged into master and was just hanging out in branch 140. I've created a PR to merge this update to master.

**Comment by emimaesmith** [comment]
Closed via #198
