### ISSUE TITLE
seed OUTPUT_DIR environment variable name should be overrideable

### ISSUE THREAD

**Issue by cshamis** [ngageoint/seed-cli#201]
The SEED executor ALWAYS provides the output directory that the SEED must write to.  But the seed author should be able to determine the NAME of that environment variable.  If it is NOT specified in the "OUTPUTS OBJECT" section, then it may default to "OUTPUT_DIR"

**Comment by JohnPTobe** [comment]
This would require an update to the seed spec

**Comment by gisjedi** [comment]
I'd _strongly_ advise against making this change. This will entirely upend our pattern of using conventions established within the spec and add needless configuration. I'm really unclear on what use case this serves.

**Comment by cshamis** [comment]
Mark as wontfix and close.

**Comment by gisjedi** [comment]
😄 Don't have to ask me twice.
