### ISSUE TITLE
Seed CLI Validation Synced with Scale

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/seed-cli#203]
Since Seed is the gold standard of Scale jobs, the validation in the CLI should be the same that happens in Scale (and vice versa). Most notable differences are:

- Scalar resources `cpus`, `mem`, `disk`, and `sharedMem` are not required by Seed, but are for Scale

**Comment by JohnPTobe** [comment]
We need to check for mount name uniqueness and error name uniqueness in the cli and make sure we're catching name collisions properly.
