### ISSUE TITLE
Seed Publish Takes  A Long Time to Complete

### ISSUE THREAD

**Issue by emimaesmith** [ngageoint/seed-cli#206]
Seed publish command takes several minutes to complete - longer if there are more images in registry. It seems seems to be possibly validating images other than the one specified to be published. We need to speed up this command and only focus on the image that's being published.

**Comment by JohnPTobe** [comment]
The v2 changes in seed-common still didn't address this issue.  I'm going to look into adding a method to the registry code that simply checks for a single image. This will also address getting irrelevant errors from other images when publishing
