### ISSUE TITLE
Polish CLI

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/seed-cli#216]
There are several minor text formatting bugs introduced in the unpublish update (1.2.0):

The -o flag s used for both output and organization.  This hasn't caused problems because no command uses both flags but it should be changed to prevent confusion. We probably want to change organization to a capital O.

The run command help has spacing issues where the new manifest flag doesn't line up properly.
The unpublish command help has the same spacing issue.
We should remove excess spaces in the example run command.
Org is optional and possibly should be omitted in example commands.
Make example text include same hints in publish/unpublish commands.

We should go back to the full width SEED graphic on the version page.

**Comment by gisjedi** [comment]
FYI the Seed graphic change for version is _not_ included in #223

**Comment by cshamis** [comment]
Full page width color ascii art logo on the -v version page.  A plain title (no ascii art) the rest of the time please.
