### ISSUE TITLE
Organization ignored with unpublish

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/seed-cli#218]
**Description**
When using `seed unpublish -in some-name -o some-org -r some.registry.com` command the `-o` flag is ignored.

**Reproduction Steps**
Steps to reproduce the problem:
1. Push an image to some.registry.com/some-org/some-name
2. Run `seed unpublish -in some-name -o some-org -r some.registry.com`

**Expected behavior**
I expected it to honor the organization setting.

**Version and Environment Details**
 - OS: Centos 7
 - Seed CLI: 1.2.0

**Comment by gisjedi** [comment]
Note that `-in some-org/some-name` flag can be used as a workaround.

**Comment by cshamis** [comment]
Is it -o or -O ?  Big O was supposed to be universally for -Org.  Little -o already had considerable expectations for "output".

**Comment by gisjedi** [comment]
Good point. It is `-o`. This inconsistency is noted in https://github.com/ngageoint/seed-cli/issues/216

**Comment by cshamis** [comment]
I'm good for some things.
