### ISSUE TITLE
Warn users of lower-case settings or inputs

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/seed-cli#225]
**Paint Point? Please describe.**
Users authoring seed manifests have quite often run into problems when injecting environment variables at run-time with the inconsistency between manifest names and the normalized variable names that are injected.

**Desired Solution**
We should either warn users on validate and build if any settings or input names are not in normal case. This is also identified in the Seed spec issue https://github.com/ngageoint/seed/issues/136. Doing this now in the CLI will prepare users for this potential change and is a best practice for consistency.

**Comment by emimaesmith** [comment]
We will update the Seed CLI to strongly warn if inconsistency is detected during validation. We will also add a flag during validation to allow treating errors as warning.

**Comment by emimaesmith** [comment]
Warning:
![image](https://user-images.githubusercontent.com/29577288/68946691-98907100-0781-11ea-9af2-e74a068689dd.png)

Warnings as Errors:
![image](https://user-images.githubusercontent.com/29577288/68946727-ad6d0480-0781-11ea-9cb5-abc65d5e4aa8.png)
