### ISSUE TITLE
Report cpu usage

### ISSUE THREAD

**Issue by icy-gisjedi** [ngageoint/seed-cli#30]
<a href="https://github.com/JohnPTobe"><img src="https://avatars2.githubusercontent.com/u/28606208?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JohnPTobe](https://github.com/JohnPTobe)**
_Wednesday Jul 19, 2017 at 19:54 GMT_
_Originally opened as https://github.com/ngageoint/seed/issues/30_

----

Report the cpu usage for a image when running through the test runner

**Comment by gisjedi** [comment]
Closing in deference to #227
