### ISSUE TITLE
CLI Batch Run mode

### ISSUE THREAD

**Issue by icy-gisjedi** [ngageoint/seed-cli#39]
<a href="https://github.com/gisjedi"><img src="https://avatars0.githubusercontent.com/u/4768496?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gisjedi](https://github.com/gisjedi)**
_Tuesday Jul 25, 2017 at 18:59 GMT_
_Originally opened as https://github.com/ngageoint/seed/issues/39_

----

We need to allow for a couple types of batch executions with the `seed run` command or create a new command to support.

We should be able to pass a directory of files to the runner for a single input files. This will cause the runner to run an instance of the job for each file found within the directory. The output dir should generate output from each iteration with a unique sub-directory allowing correlation back to input.

Once the entire batch of runs are complete we should output a result a summary grid indicating pass/fail for each input along with exit codes. Bonus points if we can spit out a file in junit compatible format.

**Comment by gisjedi** [comment]
Closed in #111
