### ISSUE TITLE
Remove build from run command

### ISSUE THREAD

**Issue by icy-gisjedi** [ngageoint/seed-cli#50]
<a href="https://github.com/JohnPTobe"><img src="https://avatars2.githubusercontent.com/u/28606208?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JohnPTobe](https://github.com/JohnPTobe)**
_Monday Jul 31, 2017 at 17:34 GMT_
_Originally opened as https://github.com/ngageoint/seed/issues/50_

----

Separate the build and run commands for clarity.  Run should only run the image, not attempt to build one.

**Comment by JohnPTobe** [comment]
This has been fixed already while working other issues.
