### ISSUE TITLE
Implement Docker Registry v2 Search

### ISSUE THREAD

**Issue by gisjedi** [ngageoint/seed-cli#74]
Implement Docker Registry V2 catalog lookup with CLI. There should not be any need to identify the backend by the user, we should have a factory to introspect the backend.

I'd anticipate us doing the following:

- Use /v2/catalog endpoint to list images
- Find all images ending with `-seed` suffix
- Pull down the single layer that has the `com.ngageoint.seed.manifest` LABEL 
- Ensure that the `seedVersion` member value is supported.

**Comment by gisjedi** [comment]
@JohnPTobe I believe this has been added by your recent work. Please link to PR or commit hash and close.

**Comment by JohnPTobe** [comment]
Fixed by PR #128 with seed-common changes made here: https://github.com/ngageoint/seed-common/commit/59debdd206b0a4ebf12510b1c53d82e1cd132d31
