### ISSUE TITLE
Display running output when running seed images

### ISSUE THREAD

**Issue by JohnPTobe** [ngageoint/seed-cli#81]
Currently the seed run command executes the specified seed image and doesn't display the output until it's done.  It would be helpful to display output as it is running so the user can see it is working and doesn't think the algorithm locked up.

**Comment by emimaesmith** [comment]
This should have been accomplished by assigning the both the stdout and stdin of the run command to os.Stderr (what we're printing output to):

`dockerRun := exec.Command("docker", dockerArgs...)`
`var errs bytes.Buffer`
`dockerRun.Stderr = io.MultiWriter(os.Stderr, &errs)`
`dockerRun.Stdout = os.Stderr`

Doing this does not require us to collect then print out any std out.

**Comment by JohnPTobe** [comment]
Tested and confirmed that the current version displays running output.
